"""Enums and constants for the EnrolHQ API."""

from enum import Enum, IntEnum


class ApplicationStatus(IntEnum):
    REGISTER_INTEREST = -1
    ENQUIRY_ONLINE = 0
    ENQUIRY_EVENT = 1
    EOI = 2
    ENROLMENT = 3
    ORIENTATION = 4
    COMMUNITY = 5
    ALUMNI = 6
    TRASHED = 7
    DECLINED = 8
    WAITLIST = 9
    RESERVED_OFFER = 10
    NOT_PROCEEDING = 11
    ENROLMENT_OFFER = 12
    INTERVIEW = 13
    PENDING = 14
    CUSTOM_1 = 15
    CUSTOM_2 = 16
    CUSTOM_3 = 17
    CUSTOM_4 = 18
    CUSTOM_5 = 19
    CUSTOM_6 = 20
    CUSTOM_7 = 21
    CUSTOM_8 = 22


class Gender(IntEnum):
    MALE = 1
    FEMALE = 2
    OTHER = 3
    PREFER_NOT_TO_DISCLOSE = 4


class DocumentKind(str, Enum):
    BIRTH_CERT = "BIRTH_CERT"
    SCHOOL_REPORT = "SCHOOL_REPORT"
    NAPLAN = "NAPLAN"
    IHS = "IHS"
    PASSPORT = "PASSPORT"
    VISA = "VISA"
    STAFF_ONLY = "STAFF_ONLY"
    SYSTEM = "SYSTEM"
    CUSTOM_FORM = "CUSTOM_FORM"
    ASSESSMENT = "ASSESSMENT"
    ENRICHMENT = "ENRICHMENT"
    MUSIC = "MUSIC"
    SPORT = "SPORT"
    DIAGNOSIS = "DIAGNOSIS"
    IEP = "IEP"
    BAPTISMAL_CERT = "BAPTISMAL_CERT"
    RECONCILIATION_CERT = "RECONCILIATION_CERT"
    COMMUNION_CERT = "COMMUNION_CERT"
    CONFIRMATION_CERT = "CONFIRMATION_CERT"
    PAYER_IDENTIFICATION = "PAYER_IDENTIFICATION"
    ABORIGINAL = "ABORIGINAL"
    CUSTODY = "CUSTODY"
    AUSTRALIAN_PASSPORT = "AUSTRALIAN_PASSPORT"
    PERMANENT_RESIDENT = "PERMANENT_RESIDENT"
    SYLLABUS = "SYLLABUS"
    SUPPORTING_MEDICAL = "SUPPORTING_MEDICAL"
    CUSTOM_1 = "CUSTOM_1"
    CUSTOM_2 = "CUSTOM_2"
    CUSTOM_3 = "CUSTOM_3"
    CUSTOM_4 = "CUSTOM_4"
    CUSTOM_5 = "CUSTOM_5"
    CUSTOM_ABILITIES_1 = "CUSTOM_ABILITIES_1"
    CUSTOM_ABILITIES_2 = "CUSTOM_ABILITIES_2"
    CUSTOM_ABILITIES_3 = "CUSTOM_ABILITIES_3"
    PARENT_PASSPORT = "PARENT_PASSPORT"
    PARENT_VISA = "PARENT_VISA"
    PARENT_HEALTH_CARE_CARD = "PARENT_HEALTH_CARE_CARD"
    PARENT_AUSTRALIAN_PASSPORT = "PARENT_AUSTRALIAN_PASSPORT"
    PARENT_PERMANENT_RESIDENT = "PARENT_PERMANENT_RESIDENT"
    PARENT_IDENTIFICATION = "PARENT_IDENTIFICATION"
    PARENT_ABORIGINAL = "PARENT_ABORIGINAL"
    INNER = "INNER"
    PARENT_DASHBOARD_DOWNLOADS = "PARENT_DASHBOARD_DOWNLOADS"
    AUTHORISED_STAFF_ONLY = "AUTHORISED_STAFF_ONLY"
